### ISSUE TITLE
Plugin has crashed

### ISSUE THREAD

**Issue by THE-SIMPLE-MARK** [Ertego/gog-galaxy-discord#6]
Hi!
I wanted to try this plugin, but It is crashing every time I want to connect.
![asd1](https://user-images.githubusercontent.com/57036815/78784216-3987fe80-79a5-11ea-984c-20a9a3945eb8.png)

**Comment by lele-blue** [comment]
Can you please attach the logfile of the plugin (The files with itch in the name located at `C:\ProgramData\GOG.COM\Galaxy\logs`)?

**Comment by lele-blue** [comment]
As there was no further correspondence, i'll close this task.
Feel free to reopen it at any time if you need more help :)

**Comment by FF7CloudsNobody** [comment]
gonna make a new issue and attach whatever logs i can find in the logs folder that may have info on this plugin
